# Generated by Django 3.2 on 2021-05-05 14:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdsDomains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='domain', to='ads.adsdomains')),
            ],
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(max_length=200)),
                ('weburl', models.CharField(max_length=255)),
                ('adsdec', models.TextField(max_length=400)),
                ('adimg', models.ImageField(default='images/NLP_WATTSAPP.png', upload_to='images/')),
                ('pubtime', models.DateTimeField(default=datetime.datetime(2021, 5, 5, 14, 46, 6, 356292, tzinfo=utc))),
                ('is_active', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20)),
                ('tags', models.ManyToManyField(to='ads.Tag')),
            ],
            options={
                'ordering': ('-pubtime',),
            },
        ),
    ]
