# Generated by Django 3.2 on 2021-05-08 19:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ads_pubtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='pubtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 19, 51, 27, 610192, tzinfo=utc)),
        ),
    ]
