# Generated by Django 3.2 on 2021-05-13 23:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ads_pubtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='pubtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 23, 17, 57, 484325, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ads',
            name='tags',
            field=models.ManyToManyField(to='ads.AdsDomains'),
        ),
    ]
