# Generated by Django 3.2 on 2021-05-13 23:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20210514_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='pubtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 23, 37, 56, 586966, tzinfo=utc)),
        ),
    ]
