# Generated by Django 3.2 on 2021-05-14 00:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_ads_pubtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='pubtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 0, 44, 13, 656941, tzinfo=utc)),
        ),
    ]
