# Generated by Django 3.2 on 2021-05-14 02:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_alter_ads_pubtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='pubtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 2, 33, 18, 123276, tzinfo=utc)),
        ),
    ]
