# Generated by Django 3.2 on 2021-05-05 14:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAdsTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaned_chat', models.TextField(max_length=600)),
                ('NERval', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestp', models.DateTimeField(default=datetime.datetime(2021, 5, 5, 14, 46, 6, 371919, tzinfo=utc))),
                ('room_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='BLANKNLPHAI', max_length=600)),
                ('chat_type', models.CharField(choices=[('msg', 'msg'), ('media', 'media')], default='msg', max_length=10)),
                ('media_url', models.ImageField(default='images/NLP_WATTSAPP.png', null=True, upload_to='images/')),
                ('timestp', models.DateTimeField(default=datetime.datetime(2021, 5, 5, 14, 46, 6, 371919, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='UserAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.ManyToManyField(to='ads.AdsDomains')),
            ],
        ),
    ]
