# Generated by Django 3.2 on 2021-05-07 07:22

import chatnlp.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatnlp', '0003_auto_20210507_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='timestp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 7, 22, 9, 356389, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='media_url',
            field=models.ImageField(default='images/NLP_WATTSAPP.png', null=True, upload_to=chatnlp.models.upload_to),
        ),
        migrations.AlterField(
            model_name='chats',
            name='timestp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 7, 22, 9, 357388, tzinfo=utc)),
        ),
    ]
