# Generated by Django 3.2 on 2021-05-08 19:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatnlp', '0005_auto_20210509_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='timestp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 19, 52, 18, 309099, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='timestp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 19, 52, 18, 310100, tzinfo=utc)),
        ),
    ]
