# Generated by Django 3.2 on 2021-05-13 23:17

import chatnlp.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatnlp', '0006_auto_20210509_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userads',
            name='tags',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='room_avatar',
            field=models.ImageField(default='images/NLP_WATTSAPP.png', null=True, upload_to=chatnlp.models.upload_to),
        ),
        migrations.AddField(
            model_name='userads',
            name='automobile',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userads',
            name='clothing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userads',
            name='donation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userads',
            name='education',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userads',
            name='environment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userads',
            name='fintech',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userads',
            name='fitness',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userads',
            name='food',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userads',
            name='heathcare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userads',
            name='investment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userads',
            name='job',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userads',
            name='medical',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userads',
            name='photography',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userads',
            name='programming',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userads',
            name='sports',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userads',
            name='technology',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='chatadstags',
            name='TAGS',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='timestp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 23, 17, 57, 499952, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='timestp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 23, 17, 57, 499952, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userads',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
