# Generated by Django 3.2 on 2021-05-13 23:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatnlp', '0007_auto_20210514_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='nlp_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='timestp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 23, 37, 56, 602592, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='timestp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 23, 37, 56, 602592, tzinfo=utc)),
        ),
    ]
