# Generated by Django 3.2 on 2021-05-14 00:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatnlp', '0008_auto_20210514_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatadstags',
            name='cleaned_chat',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='timestp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 0, 38, 42, 985612, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='timestp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 0, 38, 42, 986616, tzinfo=utc)),
        ),
    ]
